config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get    '/privacy',                    to: 'static_pages#privacy'
  get    '/signup',                     to: 'users#new'
  post   '/signup',                     to: 'users#create'
  get    '/login',                      to: 'sessions#new'
  post   '/login',                      to: 'sessions#create'
  delete '/logout',                     to: 'sessions#destroy'
  get    '/auth/facebook/callback',     to: 'users#create',          as: :auth_callback
  get    '/auth/failure',               to: 'users#auth_failure',    as: :auth_failure

  resources :users do
    member do
      get :edit_pass, :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:new, :show, :create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @feed_items = current_user.feed.paginate(page: params[:page]) if logged_in?
  end

  def privacy
  end
end

app/views/static_pages/_logged_in.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/_not_logged_in.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="center jumbotron">
      <h1>Instagram</h1>

      <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>

      <p>または</p>

      <%= link_to '/auth/facebook', id: "facebook" do %>
        <i class="fab fa-facebook fa-fw"></i> Facebookでログイン
      <% end %>
    </div>
    <div class="center jumbotron">
      <h2>
        アカウントをお持ちでないですか？
        <%= link_to "登録する", signup_path %>
      </h2>
    </div>
  </div>
</div>

<style>
footer,header {
  display: none;
}
</style>

app/views/static_pages/privacy.html.erb
<p>Instagramデータに関するポリシー
このポリシーは、弊社が提供するFacebook、Instagram、Messengerおよびその他の製品や機能(以下、Facebook製品または弊社製品)をサポートするために、弊社が処理する情報について説明しています。その他のツールや詳細な情報については、Facebookの設定およびInstagramの設定をご覧ください。</p>

app/views/static_pages/top.html.erb
<% if logged_in? %>
  <%= render 'static_pages/logged_in' %>
<% else %>
  <%= render 'static_pages/not_logged_in' %>
<% end %>