config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get    '/privacy',                    to: 'static_pages#privacy'
  get    '/signup',                     to: 'users#new'
  post   '/signup',                     to: 'users#create'
  get    '/login',                      to: 'sessions#new'
  post   '/login',                      to: 'sessions#create'
  delete '/logout',                     to: 'sessions#destroy'
  get    '/auth/facebook/callback',     to: 'users#create',          as: :auth_callback
  get    '/auth/failure',               to: 'users#auth_failure',    as: :auth_failure

  resources :users do
    member do
      get :edit_pass, :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:new, :show, :create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:   "Relationship",
                                  foreign_key:  "follower_id",
                                  dependent:    :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :username,  presence: true, length: { maximum: 50 }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :introduce, length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :password, presence: false, on: :facebook_login
  #カラムの名前をmount_uploaderに指定
  mount_uploader :image_name, ImageUploader

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now )
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    user = User.where('email = ?', auth.info.email).first
    if user.blank?
      user = User.new
    end
    user.uid   = auth.uid
    user.username  = auth.info.name
    user.email = auth.info.email
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :edit_pass, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :edit_pass, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    auth = request.env["omniauth.auth"]
      if auth.present?
        unless @auth = Authorization.find_from_auth(auth)
          @auth = Authorization.create_from_auth(auth)
        end
      user = @auth.user
      redirect_back_or user
      else
        @user = User.new(user_params)
        if @user.save
          @user.send_activation_email
          flash[:info] = "メールを確認してアカウントを有効にしてください。"
          redirect_to root_url
        else
          render 'new'
        end
      end
  end

  #認証に失敗した際の処理
  def auth_failure 
    render 'new'
  end

  def edit
  end

  def edit_pass
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email,
                                   :password, :password_confirmation,
                                   :sex, :introduce, :website,
                                   :phone, :image_name)
    end

    # beforeアクション

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn", id: "unfollow" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_tag(user.image_name.url, size: "30x30") %>
  <%= link_to user.name, user %>
  <p><%= user.username %></p>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>プロフィールを編集する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="profile-edit">
        <h4><%= @user.username %></h4>
          <%= image_tag @user.image_name.url, size: "50x50" %>
        <%= f.file_field :image_name %>
      </div>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :username, "ユーザーネーム" %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :website, "ウェブサイト" %>
      <%= f.text_field :website, class: 'form-control' %>

      <%= f.label :introduce, "自己紹介" %>
      <%= f.text_area :introduce, class: 'form-control', size: "30x3" %>

      <div class="private">
        <p>非公開情報</p>
      </div>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :phone, "電話番号" %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :sex, '性別', class:'control-label' %>
      <%= f.select :sex, [["男性","男性"],["女性","女性"]], class: 'form-control', prompt: "選択" %>

      <%= f.submit "送信する", class: "btn btn-primary" %>

      <div class="del">
        <%= link_to "アカウントを削除する", '#' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit_pass.html.erb
<% provide(:title, 'Edit_pass user') %>
<h1>パスワードを変更</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="profile-edit">
        <h2><%= @user.username %></h2>
      </div>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更する", class: "btn btn-primary" %>

      <%= link_to "(パスワードを忘れた場合)", new_password_reset_path %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザー 一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="title">
  <%= link_to root_path, id: "logo" do %>
    Instagram
  <% end %>
</div>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :username, "ユーザーネーム" %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<style>
footer,header {
  display: none;
}
</style>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="profile">
    <div class="profile_img">
      <%= image_tag @user.image_name.url, size: "150x150" %>
    </div>
    <div class="profile-body">
      <div class="profile_line">
        <p><%= @user.username %></p>
        <% if current_user?(@user) %>
          <%= button_tag(type: "button", id: "edit", class: "mr-1 btn btn-light", data: {target: "#addApp", toggle: "modal"}) do %>
            <i class="fas fa-cog"></i>
          <% end %>
          <div class="modal fade" id="addApp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-body col-md-12">
                  <%= link_to "プロフィールを編集", edit_user_path(current_user), class: "list-group-item list-group-item-action" %>
                  <%= link_to "パスワードを変更", edit_pass_user_path(current_user), class: "list-group-item list-group-item-action" %>
                  <%= link_to "ログアウト", logout_path, method: :delete, class: "list-group-item list-group-item-action" %>
                  <button type="button" id:="id:" "cancel" ,="," class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <%= render 'follow_form' if logged_in? %>
        <% end %>
      </div>
      <div class="profile_line">
        <section class="stats">
          <h3>投稿<%= @user.microposts.count %>件</h3>
          <%= render 'shared/stats' %>
        </section>
      </div>
      <div class="profile_bottom_line">
        <h3><%= @user.name %></h3>
        <p><%= @user.introduce %></p>
        <%= link_to  "#{@user.website}", target: :_blank, rel: :noopener do %>
          <%= @user.website %>
        <% end %>
      </div>
    </div>
  </div>
  <% if @user.microposts.any? %>
    <ol class="microposts">
      <%= render @microposts %>
      <%# render micropost_path %>
    </ol>
    <%= will_paginate @microposts %>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
  <h3><%= @title %></h3>
  <% if @users.any? %>
    <ul class="users follow">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  <% end %>
</div>