config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get    '/privacy',                    to: 'static_pages#privacy'
  get    '/signup',                     to: 'users#new'
  post   '/signup',                     to: 'users#create'
  get    '/login',                      to: 'sessions#new'
  post   '/login',                      to: 'sessions#create'
  delete '/logout',                     to: 'sessions#destroy'
  get    '/auth/facebook/callback',     to: 'users#create',          as: :auth_callback
  get    '/auth/failure',               to: 'users#auth_failure',    as: :auth_failure

  resources :users do
    member do
      get :edit_pass, :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:new, :show, :create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-light">
  <div class="container">
    <%= link_to new_micropost_path, id: "post" do %>
      <i class="far fa-plus-square"></i>
    <% end %>
    <%= link_to privacy_path, id: "privacy" do %>
      <i class="fas fa-user-lock"></i>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light">
  <div class="container">
    <%= link_to root_path, id: "logo" do %>
      <i class="fab fa-instagram"></i> Instagram
    <% end %>
    <div class="searchForm">
      <form onsubmit="return goSearch()" class="searchArea">
        <input type="search" class="searchText fas" placeholder="&#xf002; 検索">
      </form>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-light">
        <%= link_to users_path, id: "index" do %>
          <i class="far fa-compass"></i>
        <% end %>
        <%= link_to "#", id: "notice" do %>
          <i class="far fa-heart"></i>
        <% end %>
        <%= link_to current_user, id: "user" do %>
          <i class="far fa-user"></i>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>